import type { Metadata } from "next";

import "./globals.css";
import { Saira  } from 'next/font/google'


const saira = Saira({
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
